# We're going to want some form of Ubuntu Zesty Zapus since the researchers patched 
# Linux kernel version 4.1 -> list of mappings to kernel versions can be found here https://askubuntu.com/questions/517136/list-of-ubuntu-versions-with-corresponding-linux-kernel-version
# Will have to mess around a bit to make sure we grab a version of 4.1 pre-patch 
# FROM ubuntu:zesty

